---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: live-link-backend=leogues/video-chat-backend
    argocd-image-updater.argoproj.io/live-link-backend.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
  name: live-link-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: image.repository
        value: leogues/video-chat-backend
      - name: service.port
        value: '8080'
      - name: livenessProbe
        value: null
      - name: readinessProbe
        value: null
      - name: image.tag
        value: "46"
      - name: autoscaling.enabled
        value: "true"
      - name: autoscaling.minReplicas
        value: "1"
      - name: autoscaling.maxReplicas
        value: "1"
      - name: ingress.enabled
        value: "true"
      - name: ingress.className
        value: "traefik"
      - name: ingress.annotations.cert-manager\.io/cluster-issuer
        value: "letsencrypt-prod"
      - name: ingress.hosts[0].host
        value: "live.leogues.com.br"
      - name: ingress.hosts[0].paths[0].path
        value: "/api/"
      - name: ingress.hosts[0].paths[0].pathType
        value: "Prefix"
      - name: ingress.tls[0].secretName
        value: "live-leogues-tls"
      - name: ingress.tls[0].hosts[0]
        value: "live.leogues.com.br"
    path: helm-charts/live-link
    repoURL: git@github.com:leogues/k3s-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true